controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
travel_cost:
    path: /api/calculate
    controller: App\Controller\TravelCostController::calculate
    methods: POST